const API = {
  DASHBOARD: `/dashboard`,
  USERS: `/users/getAll`,
  USERS_UPDATE: (id: any) => `/users/${id}`,
  USERS_DELETE: (id: any) => `/users/${id}`,
  PARTNERS: `/partner`,
  PARTNERS_UPDATE: (id: any) => `/partners/${id}`,
  PARTNERS_DELETE: (id: any) => `/partners/${id}`,
  GAMES: `/games`,
  GAMES_UPDATE: (id: any) => `/games/${id}`,
  GAMES_DELETE: (id: any) => `/games/${id}`,
  TRANSACTIONS: `/transactions`,
  TRANSACTIONS_UPDATE: (id: any) => `/transactions/${id}`,
  TRANSACTIONS_DELETE: (id: any) => `/transactions/${id}`,
  VOUCHERS: `/vouchers`,
  VOUCHERS_UPDATE: (id: any) => `/vouchers/${id}`,
  VOUCHERS_DELETE: (id: any) => `/vouchers/${id}`,
  CAMPAINS: `/campains`,
  CAMPAINS_UPDATE: (id: any) => `/campains/${id}`,
  CAMPAINS_DELETE: (id: any) => `/campains/${id}`,
  AUTH: {
    LOGIN: `users/login`,
    REGISTER: `users/register`,
    CHANGE_PASSWORD: `/changePassword/`,
    FORGOT_PASSWORD: `/forgetPassword`,
    FORGOT_PASSWORD_VERIFY_OTP: `/forgetPassword/verifyOtp`,
    RESET_PASSWORD: `/forgetPassword/resetPassword`,
  },
};

export default API;
